alias: Motion Light Hall Entry
description: Full before midnight -> 50% dim; after -> 10% -> off (Sonoff cooldown handled)
mode: restart
trigger:
  - platform: state
    entity_id: binary_sensor.ewelink_ms01
    from: 'off'
    to: 'on'
condition: []
action:
  - choose:
      - conditions:
          - condition: time
            before: '00:00:00'
        sequence:
          - service: light.turn_on
            data:
              brightness_pct: 100
            target:
              device_id: b3aba36507afb24400f6a8aac654d1b3
              entity_id: e947e60950c022011d92ac2ba23877b7
          - wait_for_trigger:
              - platform: state
                entity_id: binary_sensor.ewelink_ms01
                from: 'on'
                to: 'off'
          - delay:
              seconds: 60
          - service: light.turn_on
            data:
              brightness_pct: 50
            target:
              device_id: b3aba36507afb24400f6a8aac654d1b3
              entity_id: e947e60950c022011d92ac2ba23877b7
    default:
      - service: light.turn_on
        data:
          brightness_pct: 10
        target:
          device_id: b3aba36507afb24400f6a8aac654d1b3
          entity_id: e947e60950c022011d92ac2ba23877b7
      - wait_for_trigger:
          - platform: state
            entity_id: binary_sensor.ewelink_ms01
            from: 'on'
            to: 'off'
      - delay:
          seconds: 60
      - service: light.turn_off
        target:
          device_id: b3aba36507afb24400f6a8aac654d1b3
          entity_id: e947e60950c022011d92ac2ba23877b7

